name: job_connect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UID
  uuid: ^4.4.0
    
  # State Management
  provider: ^6.1.1
  
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.6
  
  # Local Database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # Authentication
  google_sign_in: ^6.2.1
  google_generative_ai: ^0.4.0
  flutter_facebook_auth: ^6.0.4
  
  # Chat & Call
  agora_rtc_engine: ^6.2.2
  intl: ^0.20.2
  
  # Utilities
  dio: ^5.4.0
  flutter_secure_storage: ^10.0.0-beta.4
  shared_preferences: ^2.5.3

  permission_handler: ^12.0.0+1
  video_player: ^2.9.5
  image_picker: ^1.1.2

  font_awesome_flutter: ^10.7.0
  country_code_picker: ^3.0.0

  google_maps_flutter: ^2.5.3
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  http: ^1.1.0
  file_picker: ^10.1.8

  flutter_staggered_animations: ^1.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_dotenv: ^5.1.0

  speech_to_text: ^7.0.0
  url_launcher: ^6.3.1
  timeago: ^3.7.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  local_auth: ^2.1.7

  flutter_pdfview: ^1.3.2 # Để xem PDF (hoặc syncfusion_flutter_pdfviewer)
  open_filex: ^4.4.0 # Để mở các loại file khác bằng ứng dụng bên ngoài

  share_plus: ^7.2.2
  package_info_plus: ^8.3.0
  pdf: ^3.11.3
  flutter_staggered_grid_view: ^0.7.0
  #flutter_local_notifications: ^19.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/fast-charge.png" 

