// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCakd2ZNCuwTlouqWq4BKjabRn4cpUzEGM',
    appId: '1:189359785129:web:687186421b6fe9b66d15b8',
    messagingSenderId: '189359785129',
    projectId: 'huit-mobile-recruit-app',
    authDomain: 'huit-mobile-recruit-app.firebaseapp.com',
    databaseURL: 'https://huit-mobile-recruit-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'huit-mobile-recruit-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJV2HzqpNBFSuqRLyxHX9ZBjOkjY65Dic',
    appId: '1:189359785129:android:b80a14d5fbfef8486d15b8',
    messagingSenderId: '189359785129',
    projectId: 'huit-mobile-recruit-app',
    databaseURL: 'https://huit-mobile-recruit-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'huit-mobile-recruit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5z-Znlf9U8BC1qTxkPUsbr8yKuhRs9v8',
    appId: '1:189359785129:ios:3bd220ec59e1db8c6d15b8',
    messagingSenderId: '189359785129',
    projectId: 'huit-mobile-recruit-app',
    databaseURL: 'https://huit-mobile-recruit-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'huit-mobile-recruit-app.firebasestorage.app',
    androidClientId: '189359785129-uci7404f6qa2qp1psgr9vqqt8m7ss4rf.apps.googleusercontent.com',
    iosClientId: '189359785129-o71oehsehof7s39mm7djmorl85cq8o5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5z-Znlf9U8BC1qTxkPUsbr8yKuhRs9v8',
    appId: '1:189359785129:ios:3bd220ec59e1db8c6d15b8',
    messagingSenderId: '189359785129',
    projectId: 'huit-mobile-recruit-app',
    databaseURL: 'https://huit-mobile-recruit-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'huit-mobile-recruit-app.firebasestorage.app',
    androidClientId: '189359785129-uci7404f6qa2qp1psgr9vqqt8m7ss4rf.apps.googleusercontent.com',
    iosClientId: '189359785129-o71oehsehof7s39mm7djmorl85cq8o5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCakd2ZNCuwTlouqWq4BKjabRn4cpUzEGM',
    appId: '1:189359785129:web:687186421b6fe9b66d15b8',
    messagingSenderId: '189359785129',
    projectId: 'huit-mobile-recruit-app',
    authDomain: 'huit-mobile-recruit-app.firebaseapp.com',
    databaseURL: 'https://huit-mobile-recruit-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'huit-mobile-recruit-app.firebasestorage.app',
  );
}
